// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#include "messages.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_context_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DemodContext_context_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_context_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GeneralMessage_context_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_context_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ScannerContext_context_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_request_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DemodRequest_request_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_request_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GeneralRequest_request_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_request_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ScannerStateRequest_request_2eproto;
namespace piscan_pb {
class ClientToServerDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ClientToServer> _instance;
} _ClientToServer_default_instance_;
class ServerToClientDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ServerToClient> _instance;
} _ServerToClient_default_instance_;
}  // namespace piscan_pb
static void InitDefaultsClientToServer_messages_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::piscan_pb::_ClientToServer_default_instance_;
    new (ptr) ::piscan_pb::ClientToServer();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::piscan_pb::ClientToServer::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<3> scc_info_ClientToServer_messages_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 3, InitDefaultsClientToServer_messages_2eproto}, {
      &scc_info_GeneralRequest_request_2eproto.base,
      &scc_info_ScannerStateRequest_request_2eproto.base,
      &scc_info_DemodRequest_request_2eproto.base,}};

static void InitDefaultsServerToClient_messages_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::piscan_pb::_ServerToClient_default_instance_;
    new (ptr) ::piscan_pb::ServerToClient();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::piscan_pb::ServerToClient::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<3> scc_info_ServerToClient_messages_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 3, InitDefaultsServerToClient_messages_2eproto}, {
      &scc_info_ScannerContext_context_2eproto.base,
      &scc_info_DemodContext_context_2eproto.base,
      &scc_info_GeneralMessage_context_2eproto.base,}};

void InitDefaults_messages_2eproto() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ClientToServer_messages_2eproto.base);
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ServerToClient_messages_2eproto.base);
}

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_messages_2eproto[2];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_messages_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_messages_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_messages_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ClientToServer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ClientToServer, type_),
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ClientToServer, generalrequest_),
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ClientToServer, scanstaterequest_),
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ClientToServer, demodrequest_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ServerToClient, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ServerToClient, type_),
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ServerToClient, scannercontext_),
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ServerToClient, demodcontext_),
  PROTOBUF_FIELD_OFFSET(::piscan_pb::ServerToClient, generalmessage_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::piscan_pb::ClientToServer)},
  { 9, -1, sizeof(::piscan_pb::ServerToClient)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::piscan_pb::_ClientToServer_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::piscan_pb::_ServerToClient_default_instance_),
};

static ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptorsTable assign_descriptors_table_messages_2eproto = {
  {}, AddDescriptors_messages_2eproto, "messages.proto", schemas,
  file_default_instances, TableStruct_messages_2eproto::offsets,
  file_level_metadata_messages_2eproto, 2, file_level_enum_descriptors_messages_2eproto, file_level_service_descriptors_messages_2eproto,
};

const char descriptor_table_protodef_messages_2eproto[] =
  "\n\016messages.proto\022\tpiscan_pb\032\rrequest.pro"
  "to\032\rcontext.proto\"\245\002\n\016ClientToServer\022,\n\004"
  "type\030\001 \001(\0162\036.piscan_pb.ClientToServer.Ty"
  "pe\0221\n\016generalRequest\030\002 \001(\0132\031.piscan_pb.G"
  "eneralRequest\0228\n\020scanStateRequest\030\003 \001(\0132"
  "\036.piscan_pb.ScannerStateRequest\022-\n\014demod"
  "Request\030\004 \001(\0132\027.piscan_pb.DemodRequest\"I"
  "\n\004Type\022\023\n\017GENERAL_REQUEST\020\000\022\031\n\025SCANNER_S"
  "TATE_REQUEST\020\001\022\021\n\rDEMOD_REQUEST\020\002\"\230\002\n\016Se"
  "rverToClient\022,\n\004type\030\001 \001(\0162\036.piscan_pb.S"
  "erverToClient.Type\0221\n\016scannerContext\030\002 \001"
  "(\0132\031.piscan_pb.ScannerContext\022-\n\014demodCo"
  "ntext\030\003 \001(\0132\027.piscan_pb.DemodContext\0221\n\016"
  "generalMessage\030\004 \001(\0132\031.piscan_pb.General"
  "Message\"C\n\004Type\022\023\n\017SCANNER_CONTEXT\020\000\022\021\n\r"
  "DEMOD_CONTEXT\020\001\022\023\n\017GENERAL_MESSAGE\020\002b\006pr"
  "oto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_messages_2eproto = {
  false, InitDefaults_messages_2eproto, 
  descriptor_table_protodef_messages_2eproto,
  "messages.proto", &assign_descriptors_table_messages_2eproto, 644,
};

void AddDescriptors_messages_2eproto() {
  static constexpr ::PROTOBUF_NAMESPACE_ID::internal::InitFunc deps[2] =
  {
    ::AddDescriptors_request_2eproto,
    ::AddDescriptors_context_2eproto,
  };
 ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_messages_2eproto, deps, 2);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_messages_2eproto = []() { AddDescriptors_messages_2eproto(); return true; }();
namespace piscan_pb {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ClientToServer_Type_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&assign_descriptors_table_messages_2eproto);
  return file_level_enum_descriptors_messages_2eproto[0];
}
bool ClientToServer_Type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr ClientToServer_Type ClientToServer::GENERAL_REQUEST;
constexpr ClientToServer_Type ClientToServer::SCANNER_STATE_REQUEST;
constexpr ClientToServer_Type ClientToServer::DEMOD_REQUEST;
constexpr ClientToServer_Type ClientToServer::Type_MIN;
constexpr ClientToServer_Type ClientToServer::Type_MAX;
constexpr int ClientToServer::Type_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ServerToClient_Type_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&assign_descriptors_table_messages_2eproto);
  return file_level_enum_descriptors_messages_2eproto[1];
}
bool ServerToClient_Type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr ServerToClient_Type ServerToClient::SCANNER_CONTEXT;
constexpr ServerToClient_Type ServerToClient::DEMOD_CONTEXT;
constexpr ServerToClient_Type ServerToClient::GENERAL_MESSAGE;
constexpr ServerToClient_Type ServerToClient::Type_MIN;
constexpr ServerToClient_Type ServerToClient::Type_MAX;
constexpr int ServerToClient::Type_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

void ClientToServer::InitAsDefaultInstance() {
  ::piscan_pb::_ClientToServer_default_instance_._instance.get_mutable()->generalrequest_ = const_cast< ::piscan_pb::GeneralRequest*>(
      ::piscan_pb::GeneralRequest::internal_default_instance());
  ::piscan_pb::_ClientToServer_default_instance_._instance.get_mutable()->scanstaterequest_ = const_cast< ::piscan_pb::ScannerStateRequest*>(
      ::piscan_pb::ScannerStateRequest::internal_default_instance());
  ::piscan_pb::_ClientToServer_default_instance_._instance.get_mutable()->demodrequest_ = const_cast< ::piscan_pb::DemodRequest*>(
      ::piscan_pb::DemodRequest::internal_default_instance());
}
class ClientToServer::HasBitSetters {
 public:
  static const ::piscan_pb::GeneralRequest& generalrequest(const ClientToServer* msg);
  static const ::piscan_pb::ScannerStateRequest& scanstaterequest(const ClientToServer* msg);
  static const ::piscan_pb::DemodRequest& demodrequest(const ClientToServer* msg);
};

const ::piscan_pb::GeneralRequest&
ClientToServer::HasBitSetters::generalrequest(const ClientToServer* msg) {
  return *msg->generalrequest_;
}
const ::piscan_pb::ScannerStateRequest&
ClientToServer::HasBitSetters::scanstaterequest(const ClientToServer* msg) {
  return *msg->scanstaterequest_;
}
const ::piscan_pb::DemodRequest&
ClientToServer::HasBitSetters::demodrequest(const ClientToServer* msg) {
  return *msg->demodrequest_;
}
void ClientToServer::clear_generalrequest() {
  if (GetArenaNoVirtual() == nullptr && generalrequest_ != nullptr) {
    delete generalrequest_;
  }
  generalrequest_ = nullptr;
}
void ClientToServer::clear_scanstaterequest() {
  if (GetArenaNoVirtual() == nullptr && scanstaterequest_ != nullptr) {
    delete scanstaterequest_;
  }
  scanstaterequest_ = nullptr;
}
void ClientToServer::clear_demodrequest() {
  if (GetArenaNoVirtual() == nullptr && demodrequest_ != nullptr) {
    delete demodrequest_;
  }
  demodrequest_ = nullptr;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClientToServer::kTypeFieldNumber;
const int ClientToServer::kGeneralRequestFieldNumber;
const int ClientToServer::kScanStateRequestFieldNumber;
const int ClientToServer::kDemodRequestFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientToServer::ClientToServer()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:piscan_pb.ClientToServer)
}
ClientToServer::ClientToServer(const ClientToServer& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_generalrequest()) {
    generalrequest_ = new ::piscan_pb::GeneralRequest(*from.generalrequest_);
  } else {
    generalrequest_ = nullptr;
  }
  if (from.has_scanstaterequest()) {
    scanstaterequest_ = new ::piscan_pb::ScannerStateRequest(*from.scanstaterequest_);
  } else {
    scanstaterequest_ = nullptr;
  }
  if (from.has_demodrequest()) {
    demodrequest_ = new ::piscan_pb::DemodRequest(*from.demodrequest_);
  } else {
    demodrequest_ = nullptr;
  }
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:piscan_pb.ClientToServer)
}

void ClientToServer::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(
      &scc_info_ClientToServer_messages_2eproto.base);
  ::memset(&generalrequest_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&generalrequest_)) + sizeof(type_));
}

ClientToServer::~ClientToServer() {
  // @@protoc_insertion_point(destructor:piscan_pb.ClientToServer)
  SharedDtor();
}

void ClientToServer::SharedDtor() {
  if (this != internal_default_instance()) delete generalrequest_;
  if (this != internal_default_instance()) delete scanstaterequest_;
  if (this != internal_default_instance()) delete demodrequest_;
}

void ClientToServer::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ClientToServer& ClientToServer::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ClientToServer_messages_2eproto.base);
  return *internal_default_instance();
}


void ClientToServer::Clear() {
// @@protoc_insertion_point(message_clear_start:piscan_pb.ClientToServer)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && generalrequest_ != nullptr) {
    delete generalrequest_;
  }
  generalrequest_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && scanstaterequest_ != nullptr) {
    delete scanstaterequest_;
  }
  scanstaterequest_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && demodrequest_ != nullptr) {
    delete demodrequest_;
  }
  demodrequest_ = nullptr;
  type_ = 0;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ClientToServer::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // .piscan_pb.ClientToServer.Type type = 1;
      case 1: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 8) goto handle_unusual;
        ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        set_type(static_cast<::piscan_pb::ClientToServer_Type>(val));
        break;
      }
      // .piscan_pb.GeneralRequest generalRequest = 2;
      case 2: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 18) goto handle_unusual;
        ptr = ctx->ParseMessage(mutable_generalrequest(), ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .piscan_pb.ScannerStateRequest scanStateRequest = 3;
      case 3: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 26) goto handle_unusual;
        ptr = ctx->ParseMessage(mutable_scanstaterequest(), ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .piscan_pb.DemodRequest demodRequest = 4;
      case 4: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 34) goto handle_unusual;
        ptr = ctx->ParseMessage(mutable_demodrequest(), ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          return ptr;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        break;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ClientToServer::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:piscan_pb.ClientToServer)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .piscan_pb.ClientToServer.Type type = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (8 & 0xFF)) {
          int value = 0;
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   int, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::piscan_pb::ClientToServer_Type >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.GeneralRequest generalRequest = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (18 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_generalrequest()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.ScannerStateRequest scanStateRequest = 3;
      case 3: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (26 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_scanstaterequest()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.DemodRequest demodRequest = 4;
      case 4: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (34 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_demodrequest()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:piscan_pb.ClientToServer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:piscan_pb.ClientToServer)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ClientToServer::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:piscan_pb.ClientToServer)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .piscan_pb.ClientToServer.Type type = 1;
  if (this->type() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // .piscan_pb.GeneralRequest generalRequest = 2;
  if (this->has_generalrequest()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, HasBitSetters::generalrequest(this), output);
  }

  // .piscan_pb.ScannerStateRequest scanStateRequest = 3;
  if (this->has_scanstaterequest()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, HasBitSetters::scanstaterequest(this), output);
  }

  // .piscan_pb.DemodRequest demodRequest = 4;
  if (this->has_demodrequest()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, HasBitSetters::demodrequest(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:piscan_pb.ClientToServer)
}

::PROTOBUF_NAMESPACE_ID::uint8* ClientToServer::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:piscan_pb.ClientToServer)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .piscan_pb.ClientToServer.Type type = 1;
  if (this->type() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // .piscan_pb.GeneralRequest generalRequest = 2;
  if (this->has_generalrequest()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, HasBitSetters::generalrequest(this), target);
  }

  // .piscan_pb.ScannerStateRequest scanStateRequest = 3;
  if (this->has_scanstaterequest()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, HasBitSetters::scanstaterequest(this), target);
  }

  // .piscan_pb.DemodRequest demodRequest = 4;
  if (this->has_demodrequest()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, HasBitSetters::demodrequest(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:piscan_pb.ClientToServer)
  return target;
}

size_t ClientToServer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:piscan_pb.ClientToServer)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .piscan_pb.GeneralRequest generalRequest = 2;
  if (this->has_generalrequest()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *generalrequest_);
  }

  // .piscan_pb.ScannerStateRequest scanStateRequest = 3;
  if (this->has_scanstaterequest()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *scanstaterequest_);
  }

  // .piscan_pb.DemodRequest demodRequest = 4;
  if (this->has_demodrequest()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *demodrequest_);
  }

  // .piscan_pb.ClientToServer.Type type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->type());
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ClientToServer::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:piscan_pb.ClientToServer)
  GOOGLE_DCHECK_NE(&from, this);
  const ClientToServer* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ClientToServer>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:piscan_pb.ClientToServer)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:piscan_pb.ClientToServer)
    MergeFrom(*source);
  }
}

void ClientToServer::MergeFrom(const ClientToServer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:piscan_pb.ClientToServer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_generalrequest()) {
    mutable_generalrequest()->::piscan_pb::GeneralRequest::MergeFrom(from.generalrequest());
  }
  if (from.has_scanstaterequest()) {
    mutable_scanstaterequest()->::piscan_pb::ScannerStateRequest::MergeFrom(from.scanstaterequest());
  }
  if (from.has_demodrequest()) {
    mutable_demodrequest()->::piscan_pb::DemodRequest::MergeFrom(from.demodrequest());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
}

void ClientToServer::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:piscan_pb.ClientToServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClientToServer::CopyFrom(const ClientToServer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:piscan_pb.ClientToServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientToServer::IsInitialized() const {
  return true;
}

void ClientToServer::Swap(ClientToServer* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientToServer::InternalSwap(ClientToServer* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(generalrequest_, other->generalrequest_);
  swap(scanstaterequest_, other->scanstaterequest_);
  swap(demodrequest_, other->demodrequest_);
  swap(type_, other->type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ClientToServer::GetMetadata() const {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::assign_descriptors_table_messages_2eproto);
  return ::file_level_metadata_messages_2eproto[kIndexInFileMessages];
}


// ===================================================================

void ServerToClient::InitAsDefaultInstance() {
  ::piscan_pb::_ServerToClient_default_instance_._instance.get_mutable()->scannercontext_ = const_cast< ::piscan_pb::ScannerContext*>(
      ::piscan_pb::ScannerContext::internal_default_instance());
  ::piscan_pb::_ServerToClient_default_instance_._instance.get_mutable()->demodcontext_ = const_cast< ::piscan_pb::DemodContext*>(
      ::piscan_pb::DemodContext::internal_default_instance());
  ::piscan_pb::_ServerToClient_default_instance_._instance.get_mutable()->generalmessage_ = const_cast< ::piscan_pb::GeneralMessage*>(
      ::piscan_pb::GeneralMessage::internal_default_instance());
}
class ServerToClient::HasBitSetters {
 public:
  static const ::piscan_pb::ScannerContext& scannercontext(const ServerToClient* msg);
  static const ::piscan_pb::DemodContext& demodcontext(const ServerToClient* msg);
  static const ::piscan_pb::GeneralMessage& generalmessage(const ServerToClient* msg);
};

const ::piscan_pb::ScannerContext&
ServerToClient::HasBitSetters::scannercontext(const ServerToClient* msg) {
  return *msg->scannercontext_;
}
const ::piscan_pb::DemodContext&
ServerToClient::HasBitSetters::demodcontext(const ServerToClient* msg) {
  return *msg->demodcontext_;
}
const ::piscan_pb::GeneralMessage&
ServerToClient::HasBitSetters::generalmessage(const ServerToClient* msg) {
  return *msg->generalmessage_;
}
void ServerToClient::clear_scannercontext() {
  if (GetArenaNoVirtual() == nullptr && scannercontext_ != nullptr) {
    delete scannercontext_;
  }
  scannercontext_ = nullptr;
}
void ServerToClient::clear_demodcontext() {
  if (GetArenaNoVirtual() == nullptr && demodcontext_ != nullptr) {
    delete demodcontext_;
  }
  demodcontext_ = nullptr;
}
void ServerToClient::clear_generalmessage() {
  if (GetArenaNoVirtual() == nullptr && generalmessage_ != nullptr) {
    delete generalmessage_;
  }
  generalmessage_ = nullptr;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ServerToClient::kTypeFieldNumber;
const int ServerToClient::kScannerContextFieldNumber;
const int ServerToClient::kDemodContextFieldNumber;
const int ServerToClient::kGeneralMessageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ServerToClient::ServerToClient()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:piscan_pb.ServerToClient)
}
ServerToClient::ServerToClient(const ServerToClient& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_scannercontext()) {
    scannercontext_ = new ::piscan_pb::ScannerContext(*from.scannercontext_);
  } else {
    scannercontext_ = nullptr;
  }
  if (from.has_demodcontext()) {
    demodcontext_ = new ::piscan_pb::DemodContext(*from.demodcontext_);
  } else {
    demodcontext_ = nullptr;
  }
  if (from.has_generalmessage()) {
    generalmessage_ = new ::piscan_pb::GeneralMessage(*from.generalmessage_);
  } else {
    generalmessage_ = nullptr;
  }
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:piscan_pb.ServerToClient)
}

void ServerToClient::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(
      &scc_info_ServerToClient_messages_2eproto.base);
  ::memset(&scannercontext_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&scannercontext_)) + sizeof(type_));
}

ServerToClient::~ServerToClient() {
  // @@protoc_insertion_point(destructor:piscan_pb.ServerToClient)
  SharedDtor();
}

void ServerToClient::SharedDtor() {
  if (this != internal_default_instance()) delete scannercontext_;
  if (this != internal_default_instance()) delete demodcontext_;
  if (this != internal_default_instance()) delete generalmessage_;
}

void ServerToClient::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ServerToClient& ServerToClient::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ServerToClient_messages_2eproto.base);
  return *internal_default_instance();
}


void ServerToClient::Clear() {
// @@protoc_insertion_point(message_clear_start:piscan_pb.ServerToClient)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && scannercontext_ != nullptr) {
    delete scannercontext_;
  }
  scannercontext_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && demodcontext_ != nullptr) {
    delete demodcontext_;
  }
  demodcontext_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && generalmessage_ != nullptr) {
    delete generalmessage_;
  }
  generalmessage_ = nullptr;
  type_ = 0;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ServerToClient::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // .piscan_pb.ServerToClient.Type type = 1;
      case 1: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 8) goto handle_unusual;
        ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        set_type(static_cast<::piscan_pb::ServerToClient_Type>(val));
        break;
      }
      // .piscan_pb.ScannerContext scannerContext = 2;
      case 2: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 18) goto handle_unusual;
        ptr = ctx->ParseMessage(mutable_scannercontext(), ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .piscan_pb.DemodContext demodContext = 3;
      case 3: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 26) goto handle_unusual;
        ptr = ctx->ParseMessage(mutable_demodcontext(), ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .piscan_pb.GeneralMessage generalMessage = 4;
      case 4: {
        if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) != 34) goto handle_unusual;
        ptr = ctx->ParseMessage(mutable_generalmessage(), ptr);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          return ptr;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        break;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ServerToClient::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:piscan_pb.ServerToClient)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .piscan_pb.ServerToClient.Type type = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (8 & 0xFF)) {
          int value = 0;
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   int, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::piscan_pb::ServerToClient_Type >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.ScannerContext scannerContext = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (18 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_scannercontext()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.DemodContext demodContext = 3;
      case 3: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (26 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_demodcontext()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .piscan_pb.GeneralMessage generalMessage = 4;
      case 4: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (34 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_generalmessage()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:piscan_pb.ServerToClient)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:piscan_pb.ServerToClient)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ServerToClient::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:piscan_pb.ServerToClient)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .piscan_pb.ServerToClient.Type type = 1;
  if (this->type() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // .piscan_pb.ScannerContext scannerContext = 2;
  if (this->has_scannercontext()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, HasBitSetters::scannercontext(this), output);
  }

  // .piscan_pb.DemodContext demodContext = 3;
  if (this->has_demodcontext()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, HasBitSetters::demodcontext(this), output);
  }

  // .piscan_pb.GeneralMessage generalMessage = 4;
  if (this->has_generalmessage()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, HasBitSetters::generalmessage(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:piscan_pb.ServerToClient)
}

::PROTOBUF_NAMESPACE_ID::uint8* ServerToClient::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:piscan_pb.ServerToClient)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .piscan_pb.ServerToClient.Type type = 1;
  if (this->type() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // .piscan_pb.ScannerContext scannerContext = 2;
  if (this->has_scannercontext()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, HasBitSetters::scannercontext(this), target);
  }

  // .piscan_pb.DemodContext demodContext = 3;
  if (this->has_demodcontext()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, HasBitSetters::demodcontext(this), target);
  }

  // .piscan_pb.GeneralMessage generalMessage = 4;
  if (this->has_generalmessage()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, HasBitSetters::generalmessage(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:piscan_pb.ServerToClient)
  return target;
}

size_t ServerToClient::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:piscan_pb.ServerToClient)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .piscan_pb.ScannerContext scannerContext = 2;
  if (this->has_scannercontext()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *scannercontext_);
  }

  // .piscan_pb.DemodContext demodContext = 3;
  if (this->has_demodcontext()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *demodcontext_);
  }

  // .piscan_pb.GeneralMessage generalMessage = 4;
  if (this->has_generalmessage()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *generalmessage_);
  }

  // .piscan_pb.ServerToClient.Type type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->type());
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ServerToClient::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:piscan_pb.ServerToClient)
  GOOGLE_DCHECK_NE(&from, this);
  const ServerToClient* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ServerToClient>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:piscan_pb.ServerToClient)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:piscan_pb.ServerToClient)
    MergeFrom(*source);
  }
}

void ServerToClient::MergeFrom(const ServerToClient& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:piscan_pb.ServerToClient)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_scannercontext()) {
    mutable_scannercontext()->::piscan_pb::ScannerContext::MergeFrom(from.scannercontext());
  }
  if (from.has_demodcontext()) {
    mutable_demodcontext()->::piscan_pb::DemodContext::MergeFrom(from.demodcontext());
  }
  if (from.has_generalmessage()) {
    mutable_generalmessage()->::piscan_pb::GeneralMessage::MergeFrom(from.generalmessage());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
}

void ServerToClient::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:piscan_pb.ServerToClient)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ServerToClient::CopyFrom(const ServerToClient& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:piscan_pb.ServerToClient)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServerToClient::IsInitialized() const {
  return true;
}

void ServerToClient::Swap(ServerToClient* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ServerToClient::InternalSwap(ServerToClient* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(scannercontext_, other->scannercontext_);
  swap(demodcontext_, other->demodcontext_);
  swap(generalmessage_, other->generalmessage_);
  swap(type_, other->type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ServerToClient::GetMetadata() const {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::assign_descriptors_table_messages_2eproto);
  return ::file_level_metadata_messages_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace piscan_pb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::piscan_pb::ClientToServer* Arena::CreateMaybeMessage< ::piscan_pb::ClientToServer >(Arena* arena) {
  return Arena::CreateInternal< ::piscan_pb::ClientToServer >(arena);
}
template<> PROTOBUF_NOINLINE ::piscan_pb::ServerToClient* Arena::CreateMaybeMessage< ::piscan_pb::ServerToClient >(Arena* arena) {
  return Arena::CreateInternal< ::piscan_pb::ServerToClient >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
