// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_request_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_request_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_request_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_request_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
void AddDescriptors_request_2eproto();
class DemodRequest;
class DemodRequestDefaultTypeInternal;
extern DemodRequestDefaultTypeInternal _DemodRequest_default_instance_;
class GeneralRequest;
class GeneralRequestDefaultTypeInternal;
extern GeneralRequestDefaultTypeInternal _GeneralRequest_default_instance_;
class ScannerStateRequest;
class ScannerStateRequestDefaultTypeInternal;
extern ScannerStateRequestDefaultTypeInternal _ScannerStateRequest_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::DemodRequest* Arena::CreateMaybeMessage<::DemodRequest>(Arena*);
template<> ::GeneralRequest* Arena::CreateMaybeMessage<::GeneralRequest>(Arena*);
template<> ::ScannerStateRequest* Arena::CreateMaybeMessage<::ScannerStateRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum GeneralRequest_RequestType {
  GeneralRequest_RequestType_SCANNER_CONTEXT = 0,
  GeneralRequest_RequestType_DEMOD_CONTEXT = 1,
  GeneralRequest_RequestType_GeneralRequest_RequestType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  GeneralRequest_RequestType_GeneralRequest_RequestType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool GeneralRequest_RequestType_IsValid(int value);
constexpr GeneralRequest_RequestType GeneralRequest_RequestType_RequestType_MIN = GeneralRequest_RequestType_SCANNER_CONTEXT;
constexpr GeneralRequest_RequestType GeneralRequest_RequestType_RequestType_MAX = GeneralRequest_RequestType_DEMOD_CONTEXT;
constexpr int GeneralRequest_RequestType_RequestType_ARRAYSIZE = GeneralRequest_RequestType_RequestType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GeneralRequest_RequestType_descriptor();
inline const std::string& GeneralRequest_RequestType_Name(GeneralRequest_RequestType value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    GeneralRequest_RequestType_descriptor(), value);
}
inline bool GeneralRequest_RequestType_Parse(
    const std::string& name, GeneralRequest_RequestType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GeneralRequest_RequestType>(
    GeneralRequest_RequestType_descriptor(), name, value);
}
enum ScannerStateRequest_NewState {
  ScannerStateRequest_NewState_SCAN = 0,
  ScannerStateRequest_NewState_HOLD = 1,
  ScannerStateRequest_NewState_MANUAL = 2,
  ScannerStateRequest_NewState_ScannerStateRequest_NewState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ScannerStateRequest_NewState_ScannerStateRequest_NewState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ScannerStateRequest_NewState_IsValid(int value);
constexpr ScannerStateRequest_NewState ScannerStateRequest_NewState_NewState_MIN = ScannerStateRequest_NewState_SCAN;
constexpr ScannerStateRequest_NewState ScannerStateRequest_NewState_NewState_MAX = ScannerStateRequest_NewState_MANUAL;
constexpr int ScannerStateRequest_NewState_NewState_ARRAYSIZE = ScannerStateRequest_NewState_NewState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ScannerStateRequest_NewState_descriptor();
inline const std::string& ScannerStateRequest_NewState_Name(ScannerStateRequest_NewState value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ScannerStateRequest_NewState_descriptor(), value);
}
inline bool ScannerStateRequest_NewState_Parse(
    const std::string& name, ScannerStateRequest_NewState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ScannerStateRequest_NewState>(
    ScannerStateRequest_NewState_descriptor(), name, value);
}
enum DemodRequest_DemodFunc {
  DemodRequest_DemodFunc_SET_SQUELCH = 0,
  DemodRequest_DemodFunc_SET_GAIN = 1,
  DemodRequest_DemodFunc_DemodRequest_DemodFunc_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  DemodRequest_DemodFunc_DemodRequest_DemodFunc_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool DemodRequest_DemodFunc_IsValid(int value);
constexpr DemodRequest_DemodFunc DemodRequest_DemodFunc_DemodFunc_MIN = DemodRequest_DemodFunc_SET_SQUELCH;
constexpr DemodRequest_DemodFunc DemodRequest_DemodFunc_DemodFunc_MAX = DemodRequest_DemodFunc_SET_GAIN;
constexpr int DemodRequest_DemodFunc_DemodFunc_ARRAYSIZE = DemodRequest_DemodFunc_DemodFunc_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DemodRequest_DemodFunc_descriptor();
inline const std::string& DemodRequest_DemodFunc_Name(DemodRequest_DemodFunc value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DemodRequest_DemodFunc_descriptor(), value);
}
inline bool DemodRequest_DemodFunc_Parse(
    const std::string& name, DemodRequest_DemodFunc* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DemodRequest_DemodFunc>(
    DemodRequest_DemodFunc_descriptor(), name, value);
}
// ===================================================================

class GeneralRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GeneralRequest) */ {
 public:
  GeneralRequest();
  virtual ~GeneralRequest();

  GeneralRequest(const GeneralRequest& from);
  GeneralRequest(GeneralRequest&& from) noexcept
    : GeneralRequest() {
    *this = ::std::move(from);
  }

  inline GeneralRequest& operator=(const GeneralRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GeneralRequest& operator=(GeneralRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GeneralRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GeneralRequest* internal_default_instance() {
    return reinterpret_cast<const GeneralRequest*>(
               &_GeneralRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(GeneralRequest* other);
  friend void swap(GeneralRequest& a, GeneralRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GeneralRequest* New() const final {
    return CreateMaybeMessage<GeneralRequest>(nullptr);
  }

  GeneralRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GeneralRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GeneralRequest& from);
  void MergeFrom(const GeneralRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GeneralRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GeneralRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef GeneralRequest_RequestType RequestType;
  static constexpr RequestType SCANNER_CONTEXT =
    GeneralRequest_RequestType_SCANNER_CONTEXT;
  static constexpr RequestType DEMOD_CONTEXT =
    GeneralRequest_RequestType_DEMOD_CONTEXT;
  static inline bool RequestType_IsValid(int value) {
    return GeneralRequest_RequestType_IsValid(value);
  }
  static constexpr RequestType RequestType_MIN =
    GeneralRequest_RequestType_RequestType_MIN;
  static constexpr RequestType RequestType_MAX =
    GeneralRequest_RequestType_RequestType_MAX;
  static constexpr int RequestType_ARRAYSIZE =
    GeneralRequest_RequestType_RequestType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  RequestType_descriptor() {
    return GeneralRequest_RequestType_descriptor();
  }
  static inline const std::string& RequestType_Name(RequestType value) {
    return GeneralRequest_RequestType_Name(value);
  }
  static inline bool RequestType_Parse(const std::string& name,
      RequestType* value) {
    return GeneralRequest_RequestType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // int32 handle = 1;
  void clear_handle();
  static const int kHandleFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int32 handle() const;
  void set_handle(::PROTOBUF_NAMESPACE_ID::int32 value);

  // .GeneralRequest.RequestType type = 2;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::GeneralRequest_RequestType type() const;
  void set_type(::GeneralRequest_RequestType value);

  // @@protoc_insertion_point(class_scope:GeneralRequest)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 handle_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_request_2eproto;
};
// -------------------------------------------------------------------

class ScannerStateRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ScannerStateRequest) */ {
 public:
  ScannerStateRequest();
  virtual ~ScannerStateRequest();

  ScannerStateRequest(const ScannerStateRequest& from);
  ScannerStateRequest(ScannerStateRequest&& from) noexcept
    : ScannerStateRequest() {
    *this = ::std::move(from);
  }

  inline ScannerStateRequest& operator=(const ScannerStateRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ScannerStateRequest& operator=(ScannerStateRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ScannerStateRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ScannerStateRequest* internal_default_instance() {
    return reinterpret_cast<const ScannerStateRequest*>(
               &_ScannerStateRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ScannerStateRequest* other);
  friend void swap(ScannerStateRequest& a, ScannerStateRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ScannerStateRequest* New() const final {
    return CreateMaybeMessage<ScannerStateRequest>(nullptr);
  }

  ScannerStateRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ScannerStateRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ScannerStateRequest& from);
  void MergeFrom(const ScannerStateRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ScannerStateRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ScannerStateRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ScannerStateRequest_NewState NewState;
  static constexpr NewState SCAN =
    ScannerStateRequest_NewState_SCAN;
  static constexpr NewState HOLD =
    ScannerStateRequest_NewState_HOLD;
  static constexpr NewState MANUAL =
    ScannerStateRequest_NewState_MANUAL;
  static inline bool NewState_IsValid(int value) {
    return ScannerStateRequest_NewState_IsValid(value);
  }
  static constexpr NewState NewState_MIN =
    ScannerStateRequest_NewState_NewState_MIN;
  static constexpr NewState NewState_MAX =
    ScannerStateRequest_NewState_NewState_MAX;
  static constexpr int NewState_ARRAYSIZE =
    ScannerStateRequest_NewState_NewState_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  NewState_descriptor() {
    return ScannerStateRequest_NewState_descriptor();
  }
  static inline const std::string& NewState_Name(NewState value) {
    return ScannerStateRequest_NewState_Name(value);
  }
  static inline bool NewState_Parse(const std::string& name,
      NewState* value) {
    return ScannerStateRequest_NewState_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // int32 handle = 1;
  void clear_handle();
  static const int kHandleFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int32 handle() const;
  void set_handle(::PROTOBUF_NAMESPACE_ID::int32 value);

  // .ScannerStateRequest.NewState state = 2;
  void clear_state();
  static const int kStateFieldNumber = 2;
  ::ScannerStateRequest_NewState state() const;
  void set_state(::ScannerStateRequest_NewState value);

  // uint64 manFreq = 3;
  void clear_manfreq();
  static const int kManFreqFieldNumber = 3;
  ::PROTOBUF_NAMESPACE_ID::uint64 manfreq() const;
  void set_manfreq(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // @@protoc_insertion_point(class_scope:ScannerStateRequest)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 handle_;
  int state_;
  ::PROTOBUF_NAMESPACE_ID::uint64 manfreq_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_request_2eproto;
};
// -------------------------------------------------------------------

class DemodRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DemodRequest) */ {
 public:
  DemodRequest();
  virtual ~DemodRequest();

  DemodRequest(const DemodRequest& from);
  DemodRequest(DemodRequest&& from) noexcept
    : DemodRequest() {
    *this = ::std::move(from);
  }

  inline DemodRequest& operator=(const DemodRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DemodRequest& operator=(DemodRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const DemodRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DemodRequest* internal_default_instance() {
    return reinterpret_cast<const DemodRequest*>(
               &_DemodRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(DemodRequest* other);
  friend void swap(DemodRequest& a, DemodRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DemodRequest* New() const final {
    return CreateMaybeMessage<DemodRequest>(nullptr);
  }

  DemodRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DemodRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DemodRequest& from);
  void MergeFrom(const DemodRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DemodRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DemodRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef DemodRequest_DemodFunc DemodFunc;
  static constexpr DemodFunc SET_SQUELCH =
    DemodRequest_DemodFunc_SET_SQUELCH;
  static constexpr DemodFunc SET_GAIN =
    DemodRequest_DemodFunc_SET_GAIN;
  static inline bool DemodFunc_IsValid(int value) {
    return DemodRequest_DemodFunc_IsValid(value);
  }
  static constexpr DemodFunc DemodFunc_MIN =
    DemodRequest_DemodFunc_DemodFunc_MIN;
  static constexpr DemodFunc DemodFunc_MAX =
    DemodRequest_DemodFunc_DemodFunc_MAX;
  static constexpr int DemodFunc_ARRAYSIZE =
    DemodRequest_DemodFunc_DemodFunc_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  DemodFunc_descriptor() {
    return DemodRequest_DemodFunc_descriptor();
  }
  static inline const std::string& DemodFunc_Name(DemodFunc value) {
    return DemodRequest_DemodFunc_Name(value);
  }
  static inline bool DemodFunc_Parse(const std::string& name,
      DemodFunc* value) {
    return DemodRequest_DemodFunc_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // int32 handle = 1;
  void clear_handle();
  static const int kHandleFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int32 handle() const;
  void set_handle(::PROTOBUF_NAMESPACE_ID::int32 value);

  // float level = 2;
  void clear_level();
  static const int kLevelFieldNumber = 2;
  float level() const;
  void set_level(float value);

  // @@protoc_insertion_point(class_scope:DemodRequest)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 handle_;
  float level_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_request_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GeneralRequest

// int32 handle = 1;
inline void GeneralRequest::clear_handle() {
  handle_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GeneralRequest::handle() const {
  // @@protoc_insertion_point(field_get:GeneralRequest.handle)
  return handle_;
}
inline void GeneralRequest::set_handle(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  handle_ = value;
  // @@protoc_insertion_point(field_set:GeneralRequest.handle)
}

// .GeneralRequest.RequestType type = 2;
inline void GeneralRequest::clear_type() {
  type_ = 0;
}
inline ::GeneralRequest_RequestType GeneralRequest::type() const {
  // @@protoc_insertion_point(field_get:GeneralRequest.type)
  return static_cast< ::GeneralRequest_RequestType >(type_);
}
inline void GeneralRequest::set_type(::GeneralRequest_RequestType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:GeneralRequest.type)
}

// -------------------------------------------------------------------

// ScannerStateRequest

// int32 handle = 1;
inline void ScannerStateRequest::clear_handle() {
  handle_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ScannerStateRequest::handle() const {
  // @@protoc_insertion_point(field_get:ScannerStateRequest.handle)
  return handle_;
}
inline void ScannerStateRequest::set_handle(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  handle_ = value;
  // @@protoc_insertion_point(field_set:ScannerStateRequest.handle)
}

// .ScannerStateRequest.NewState state = 2;
inline void ScannerStateRequest::clear_state() {
  state_ = 0;
}
inline ::ScannerStateRequest_NewState ScannerStateRequest::state() const {
  // @@protoc_insertion_point(field_get:ScannerStateRequest.state)
  return static_cast< ::ScannerStateRequest_NewState >(state_);
}
inline void ScannerStateRequest::set_state(::ScannerStateRequest_NewState value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:ScannerStateRequest.state)
}

// uint64 manFreq = 3;
inline void ScannerStateRequest::clear_manfreq() {
  manfreq_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ScannerStateRequest::manfreq() const {
  // @@protoc_insertion_point(field_get:ScannerStateRequest.manFreq)
  return manfreq_;
}
inline void ScannerStateRequest::set_manfreq(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  manfreq_ = value;
  // @@protoc_insertion_point(field_set:ScannerStateRequest.manFreq)
}

// -------------------------------------------------------------------

// DemodRequest

// int32 handle = 1;
inline void DemodRequest::clear_handle() {
  handle_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 DemodRequest::handle() const {
  // @@protoc_insertion_point(field_get:DemodRequest.handle)
  return handle_;
}
inline void DemodRequest::set_handle(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  handle_ = value;
  // @@protoc_insertion_point(field_set:DemodRequest.handle)
}

// float level = 2;
inline void DemodRequest::clear_level() {
  level_ = 0;
}
inline float DemodRequest::level() const {
  // @@protoc_insertion_point(field_get:DemodRequest.level)
  return level_;
}
inline void DemodRequest::set_level(float value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:DemodRequest.level)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::GeneralRequest_RequestType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::GeneralRequest_RequestType>() {
  return ::GeneralRequest_RequestType_descriptor();
}
template <> struct is_proto_enum< ::ScannerStateRequest_NewState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ScannerStateRequest_NewState>() {
  return ::ScannerStateRequest_NewState_descriptor();
}
template <> struct is_proto_enum< ::DemodRequest_DemodFunc> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::DemodRequest_DemodFunc>() {
  return ::DemodRequest_DemodFunc_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_request_2eproto
